---
- name: Install Jenkins on Fedora OS
  hosts: localhost
  become: yes

  #JENKINS
  tasks:
  - name: Install Java
    ansible.builtin.dnf:
      update_cache: true
      name: "{{ item }}"
      state: present
    loop:
      - fontconfig
      - java-21-openjdk #java-21-openjdk
      - java-21-openjdk-devel

  - name: Import Jenkins GPG key
    ansible.builtin.rpm_key:
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
      state: present

  - name: Add Jenkins repo
    ansible.builtin.get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
      # state: present
    
  - name: Refresh repo and Install Jenkins
    ansible.builtin.dnf:
      update_cache: true
      name: jenkins
      state: present

  - name: Start and Enable jenkins.service
    ansible.builtin.systemd_service:
      daemon_reload: true
      enabled: true
      name: jenkins.service
      state: started